### ISSUE TITLE
Consider support for osx-arm64

### ISSUE THREAD

**Issue by AlienKevin** [conda-forge/pykakasi-feedstock#15]
### Comment:

@h-vetinari Many people are now using arm-based Macs. It would be great if osx-arm64 can be added as a target in conda. Thanks!

**Comment by h-vetinari** [comment]
Please follow these [instructions](https://conda-forge.org/docs/maintainer/knowledge_base/#apple-silicon-builds)

**Comment by AlienKevin** [comment]
To track osx-arm64 migration progress...

Current state:
PR created for osx_arm64.txt: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6082

Edit:
PR merged!

Edit:
PR made to this repo to add osx arm64 support. Though the CI is not passing for some reason.

**Comment by h-vetinari** [comment]
So I fixed this in #16, but you should be aware that https://github.com/miurahr/pykakasi has been archived already ~2 years ago, and from experience it's only a question of time until things start breaking more comprehensively. Not sure if there's a follow-up project or anything else.

CC @miurahr

**Comment by AlienKevin** [comment]
@h-vetinari Thanks! I think pykakasi has been moved to Codeberg (https://codeberg.org/miurahr/pykakasi) and is still being actively maintained (new stable release 4 days ago). I raised an issue about osx arm64 support there and the author referred me to you.

**Comment by h-vetinari** [comment]
Ah, that's great to know - I had no idea (there was no indication on the github repo about the move)! Then we definitely need to switch sources, and I'll try to publish 2.3.0
